### ISSUE TITLE
Question about your plan

### ISSUE THREAD

**Issue by PorcoRosso85** [erralb/mermaid-js-erd-to-sql#1]
Hi. I did want really to use the great tool like this.

If we use great tool on any OS, I always check whether that tool provide features as CLI or not.
Do you have plan for this?

- core: core of this app ( parse mermaid <-> sql / sql <-> any engines like pg, mysql, sqlite,,, )
- cli: cli for core
  - command to pg
  - command to mysql
  - ...
- ext: vscode extension API and mermaid viewer etc...

**Comment by erralb** [comment]
Hi and thank you for you interest and suggestion.

Right now I am focusing on finalising the VSCode extension (testing and documentation), but I will look into a cli version when I am done.
